### ISSUE TITLE
Does this still compile?

### ISSUE THREAD

**Issue by AnthonyCC** [Adobe-Marketing-Cloud/aem-authoring-dialog-fields-customization#2]
Not sure if this still support anymore. I am having tons of error when I try to compile it? Can a maintainer confirm this should still compile?

**Comment by martinischeery** [comment]
@AnthonyCC I just tried to compile it and got no issues. Please note that the master branch has been recently updated for 6.3 support (we'll soon create a maintenance branch for 6.2 though)

*EDIT:* I was using the wrong profile --I'll have a look at it

**Comment by martinischeery** [comment]
Could you please give it another try with https://github.com/Adobe-Marketing-Cloud/aem-authoring-dialog-fields-customization/commit/779833c49c28c35a8828f1f353349c4dd41c0d4b?
